//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        public int HotelId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public string HotelName { get; set; }
        public string HotelEmail { get; set; }
        public string HotelContactPerson { get; set; }
        public string HotelPhoneNumber { get; set; }
    }
}
