//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Units = new HashSet<Unit>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public int ItemCategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Unit> Units { get; set; }
    }
}
